create table if not exists public.social_links (
  id bigint generated by default as identity primary key,
  platform text not null check (platform in ('whatsapp', 'facebook', 'instagram', 'threads', 'tiktok')),
  label text not null,
  url text not null,
  enabled boolean not null default true,
  display_order integer not null default 0,
  created_at timestamp with time zone not null default now()
);

alter table public.social_links enable row level security;

create policy "Allow public read social links"
on public.social_links
for select
using (true);

create policy "Allow authenticated users to manage social links"
on public.social_links
for all
to authenticated
using (true)
with check (true);
